# Generated by Django 2.2 on 2019-04-26 10:06

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ITtestapp', '0002_auto_20190426_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ittest',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='富文本'),
        ),
    ]
