# Generated by Django 2.2 on 2019-04-26 10:20

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ITtestapp', '0003_auto_20190426_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ittest',
            name='content',
            field=mdeditor.fields.MDTextField(verbose_name='富文本'),
        ),
    ]
